In [ ]:
# 데이터 분석할 파일 /content/korean-idol.csv

In [1]:
# csv파일을 불러와서 제일 앞에 5개 행을 보여줘

import pandas as pd
df = pd.read_csv('/content/korean-idol.csv')
df.head()

     이름     그룹  소속사  성별        생년월일      키 혈액형   브랜드평판지수
0    지민  방탄소년단  빅히트  남자  1995-10-13  173.6   A  10523260
1  지드래곤     빅뱅   YG  남자  1988-08-18  177.0   A   9916947
2  강다니엘    NaN  커넥트  남자  1996-12-10  180.0   A   8273745
3     뷔  방탄소년단  빅히트  남자  1995-12-30  178.0  AB   8073501
4    화사    마마무  RBW  여자  1995-07-23  162.1   A   7650928

In [2]:
# csv에서 읽어온 사람들 중에 키가 제일 큰 사람과 작은 사람을 알려줘

tallest_person = df.loc[df['키'].idxmax()]
shortest_person = df.loc[df['키'].idxmin()]

print(f"키가 가장 큰 사람: {tallest_person['이름']} (키: {tallest_person['키']}cm)")
print(f"키가 가장 작은 사람: {shortest_person['이름']} (키: {shortest_person['키']}cm)")

키가 가장 큰 사람: 차은우 (키: 183.0cm)
키가 가장 작은 사람: 화사 (키: 162.1cm)

In [3]:
# 혈액형이 A형인 사람의 목록을 출력해줘

blood_type_a_people = df[df['혈액형'] == 'A']
print("혈액형이 A형인 사람:")
for name in blood_type_a_people['이름']:
    print(name)

혈액형이 A형인 사람:
지민
지드래곤
강다니엘
화사
정국
하성운
태연

In [7]:
# 키컬럼에 NaN이 있는데 평균값으로 채워줘

mean_height = df['키'].mean()
df['키'] = df['키'].fillna(mean_height)

print(f"키 컬럼의 평균값: {mean_height:.2f}")
print("NaN 값 처리 후 '키' 컬럼의 정보:")
df.info()

키 컬럼의 평균값: 175.79
NaN 값 처리 후 '키' 컬럼의 정보:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 8 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   이름       15 non-null     object
 1   그룹       14 non-null     object
 2   소속사      15 non-null     object
 3   성별       15 non-null     object
 4   생년월일     15 non-null     object
 5   키        15 non-null     float64
 6   혈액형      15 non-null     object
 7   브랜드평판지수  15 non-null     int64
dtypes: float64(1), int64(1), object(6)
memory usage: 1.1+ KB

In [6]:
display(df)

      이름     그룹      소속사  성별        생년월일           키 혈액형   브랜드평판지수
0     지민  방탄소년단      빅히트  남자  1995-10-13  173.600000   A  10523260
1   지드래곤     빅뱅       YG  남자  1988-08-18  177.000000   A   9916947
2   강다니엘    NaN      커넥트  남자  1996-12-10  180.000000   A   8273745
3      뷔  방탄소년단      빅히트  남자  1995-12-30  178.000000  AB   8073501
4     화사    마마무      RBW  여자  1995-07-23  162.100000   A   7650928
5     정국  방탄소년단      빅히트  남자  1997-09-01  178.000000   A   5208335
6     민현   뉴이스트     플레디스  남자  1995-08-09  182.300000   O   4989792
7     소연    아이들       큐브  여자  1998-08-26  175.792308   B   4668615
8      진  방탄소년단      빅히트  남자  1992-12-04  179.200000   O   4570308
9    하성운     핫샷  스타크루이엔티  남자  1994-03-22  167.100000   A   4036489
10    태연   소녀시대       SM  여자  1989-03-09  175.792308   A   3918661
11   차은우   아스트로     판타지오  남자  1997-03-30  183.000000   B   3506027
12    백호   뉴이스트     플레디스  남자  1995-07-21  175.000000  AB   3301654
13    JR   뉴이스트     플레디스  남자  1995-06-08  176.000000   O   3274137
14    슈가  방탄소년단      빅히트  남자  1993-03-09  174.000000   O   2925442

In [11]:
df_sorted_by_height = df.sort_values(by='키')
display(df_sorted_by_height)

      이름     그룹      소속사  성별        생년월일           키 혈액형   브랜드평판지수
4     화사    마마무      RBW  여자  1995-07-23  162.100000   A   7650928
9    하성운     핫샷  스타크루이엔티  남자  1994-03-22  167.100000   A   4036489
0     지민  방탄소년단      빅히트  남자  1995-10-13  173.600000   A  10523260
14    슈가  방탄소년단      빅히트  남자  1993-03-09  174.000000   O   2925442
12    백호   뉴이스트     플레디스  남자  1995-07-21  175.000000  AB   3301654
10    태연   소녀시대       SM  여자  1989-03-09  175.792308   A   3918661
7     소연    아이들       큐브  여자  1998-08-26  175.792308   B   4668615
13    JR   뉴이스트     플레디스  남자  1995-06-08  176.000000   O   3274137
1   지드래곤     빅뱅       YG  남자  1988-08-18  177.000000   A   9916947
5     정국  방탄소년단      빅히트  남자  1997-09-01  178.000000   A   5208335
3      뷔  방탄소년단      빅히트  남자  1995-12-30  178.000000  AB   8073501
8      진  방탄소년단      빅히트  남자  1992-12-04  179.200000   O   4570308
2   강다니엘    NaN      커넥트  남자  1996-12-10  180.000000   A   8273745
6     민현   뉴이스트     플레디스  남자  1995-08-09  182.300000   O   4989792
11   차은우   아스트로     판타지오  남자  1997-03-30  183.000000   B   3506027

In [9]:
# 그럼 수정된 내용을 result.csv파일로 저장해줘

df.to_csv('result.csv', index=False)
print("DataFrame이 'result.csv' 파일로 저장되었습니다.")

DataFrame이 'result.csv' 파일로 저장되었습니다.

In [10]:
pd.read_csv('result.csv').head()

     이름     그룹  소속사  성별        생년월일      키 혈액형   브랜드평판지수
0    지민  방탄소년단  빅히트  남자  1995-10-13  173.6   A  10523260
1  지드래곤     빅뱅   YG  남자  1988-08-18  177.0   A   9916947
2  강다니엘    NaN  커넥트  남자  1996-12-10  180.0   A   8273745
3     뷔  방탄소년단  빅히트  남자  1995-12-30  178.0  AB   8073501
4    화사    마마무  RBW  여자  1995-07-23  162.1   A   7650928

In [8]:
print("현재 '키' 컬럼의 NaN 값 확인:")
print(df['키'].isnull().sum())
display(df)

현재 '키' 컬럼의 NaN 값 확인:
0

      이름     그룹      소속사  성별        생년월일           키 혈액형   브랜드평판지수
0     지민  방탄소년단      빅히트  남자  1995-10-13  173.600000   A  10523260
1   지드래곤     빅뱅       YG  남자  1988-08-18  177.000000   A   9916947
2   강다니엘    NaN      커넥트  남자  1996-12-10  180.000000   A   8273745
3      뷔  방탄소년단      빅히트  남자  1995-12-30  178.000000  AB   8073501
4     화사    마마무      RBW  여자  1995-07-23  162.100000   A   7650928
5     정국  방탄소년단      빅히트  남자  1997-09-01  178.000000   A   5208335
6     민현   뉴이스트     플레디스  남자  1995-08-09  182.300000   O   4989792
7     소연    아이들       큐브  여자  1998-08-26  175.792308   B   4668615
8      진  방탄소년단      빅히트  남자  1992-12-04  179.200000   O   4570308
9    하성운     핫샷  스타크루이엔티  남자  1994-03-22  167.100000   A   4036489
10    태연   소녀시대       SM  여자  1989-03-09  175.792308   A   3918661
11   차은우   아스트로     판타지오  남자  1997-03-30  183.000000   B   3506027
12    백호   뉴이스트     플레디스  남자  1995-07-21  175.000000  AB   3301654
13    JR   뉴이스트     플레디스  남자  1995-06-08  176.000000   O   3274137
14    슈가  방탄소년단      빅히트  남자  1993-03-09  174.000000   O   2925442